version: '3.8'
services:
  movies:
    image: ramyatraining/paytmmoviess:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: ramyatraining/paytmtrainn:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: ramyatraining/paytmdthh:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: ramyatraining/paytmrechargee:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
